### ISSUE TITLE
各マイニングプールの情報を表示する。

### ISSUE THREAD

**Issue by Yocchan1513** [yocchan1513-team/zny-info#27]
## 各マイニングプールの情報を表示
:package: APIが取得できるのでそれを使ってマイニングプールの情報を表示できるようにしたい。

**Comment by zinntikumugai** [comment]
https://pools.currency.ovh/json/bitzeny.json
よかったらどうぞ

**Comment by Yocchan1513** [comment]
ありがとうございます
