### ISSUE TITLE
ぜにいんふぉに何が必要か?

### ISSUE THREAD

**Issue by Yocchan1513** [yocchan1513-team/zny-info#29]
## :art:ぜにいんふぉに必要な物を書いておく場所

**Comment by fujiwaraizuho** [comment]
なんかひとつひとつの要素がバラバラしてて色んな方向に向いている気がする。
ぜにいんふぉとしての立ち位置を明確にしてどんなユーザーにどんな情報を届けたいのかを考える必要があるのかもしれない
私はBitZeny Wikiの代わりになることを期待している

**Comment by Yocchan1513** [comment]
なるほど...
