### ISSUE TITLE
ゼニマの表示名について

### ISSUE THREAD

**Issue by fujiwaraizuho** [yocchan1513-team/zny-info#30]
ゼニマのTwitterアカウントへリンクを貼ってくださるのはたいへん有難いのですが出来れば開発中である旨併記して下さると助かります。

**Comment by Yocchan1513** [comment]
記載しました
![コメント 2019-08-18 001836](https://user-images.githubusercontent.com/19615493/63213988-c1d33e00-c14d-11e9-85c5-9946baa6428c.png)
